name: Build & Release

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.x
          cache: npm
      - name: Install
        run: npm install
      - name: Make
        if: startsWith(github.ref, 'refs/tags/')
        run: electron-builder --all
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            build/*Setup*.exe
